# Generated by Django 3.0.4 on 2020-03-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='times_visited',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='original_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
